package com.codingchallenge.locations.enums;

public enum LocationType {
    RESTAURANT, PARK, MUSEUM, CAFE, BAR, SHOPPING_MALL, THEATER, LIBRARY, GYM, HOSPITAL, SCHOOL, HOTEL, STADIUM, ZOO, AQUARIUM, BEACH, LANDMARK, HISTORICAL_SITE, ART_GALLERY, NIGHTCLUB
}
